# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: mdillion/postgis:10
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: iltickets

      # Postgres is required for database tests
      #- image: circleci/postgres:10.5

    working_directory: ~/repo

    environment:
        ILTICKETS_DB_URL: postgres://circleci:@localhost/iltickets
        ILTICKETS_DB_ROOT_URL: postgres://circleci:@localhost
        ILTICKETS_DB_NAME: iltickets
        ILTICKETS_DB_STRING: "dbname=iltickets dbuser=circleci"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install postgresql-client postgis

      - run:
          name: Install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run make
          command: make YEARS=2018 all

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest .

      - store_artifacts:
          path: test-reports
          destination: test-reports
