create table if not exists public.acs_16_5yr_b02001 (
  id character varying,
  geoid character varying,
  geography character varying,
  total bigint,
  total_moe bigint,
  white bigint,
  white_moe bigint,
  black bigint,
  black_moe bigint,
  native bigint,
  native_moe bigint,
  asian bigint,
  asian_moe bigint,
  pacific_islander bigint,
  pacific_islander_moe bigint,
  other bigint,
  other_moe bigint,
  two_or_more bigint,
  two_or_more_moe bigint,
  two_or_more_including_other bigint,
  two_or_more_including_other_moe bigint,
  three_or_more bigint,
  three_or_more_moe bigint
)
