CREATE TABLE public.cameras (
  ticket_number bigint primary key,
  issue_date timestamp without time zone,
  violation_location character varying,
  license_plate_number character varying,
  license_plate_state character varying,
  license_plate_type character varying,
  zipcode character varying,
  violation_code character varying,
  violation_description character varying,
  unit character varying,
  unit_description character varying,
  vehicle_make character varying,
  fine_level1_amount double precision,
  fine_level2_amount double precision,
  current_amount_due double precision,
  total_payments double precision,
  ticket_queue character varying,
  ticket_queue_date timestamp without time zone,
  notice_level character varying,
  hearing_disposition character varying,
  notice_number bigint,
  officer character varying
);
