create table community_area_stats (
	"geog" varchar not null,
	"2000_pop" decimal not null,
	"2010_pop" decimal not null,
	"pop_change" decimal not null,
	"tot_pop" decimal not null,
	"und19" decimal not null,
	"a20_34" decimal not null,
	"a35_49" decimal not null,
	"a50_64" decimal not null,
	"a65_79" decimal not null,
	"ov80" decimal not null,
	"med_age" decimal not null,
	"white" decimal not null,
	"hisp" decimal not null,
	"black" decimal not null,
	"asian" decimal not null,
	"other" decimal not null,
	"pop_hh" decimal not null,
	"pop_16ov" decimal not null,
	"in_lbfrc" decimal not null,
	"emp" decimal not null,
	"unemp" decimal not null,
	"not_in_lbfrc" decimal not null,
	"work_at_home" decimal not null,
	"tot_comm" decimal not null,
	"drove_al" decimal not null,
	"carpool" decimal not null,
	"transit" decimal not null,
	"walk_bike" decimal not null,
	"comm_other" decimal not null,
	"pop_25ov" decimal not null,
	"hs" decimal not null,
	"bach" decimal not null,
	"inc_lt_25k" decimal not null,
	"inc_25_50k" decimal not null,
	"inc_50_75k" decimal not null,
	"inc_75_100k" decimal not null,
	"inc_100_150k" decimal not null,
	"inc_gt_150" decimal not null,
	"medinc" decimal not null,
	"tot_hh" decimal not null,
	"own_occ_hu" decimal not null,
	"rent_occ_hu" decimal not null,
	"vac_hu" decimal not null,
	"hu_tot" decimal not null,
	"hu_sng_det" decimal not null,
	"hu_sng_att" decimal not null,
	"hu_2un" decimal not null,
	"hu_3_4un" decimal not null,
	"hu_gt_5un" decimal not null,
	"med_rooms" decimal not null,
	"ha_aft2000" decimal not null,
	"ha_70_00" decimal not null,
	"ha_40_70" decimal not null,
	"ha_bef1940" decimal not null,
	"med_ha" decimal not null,
	"br_0_1" decimal not null,
	"br_2" decimal not null,
	"br_3" decimal not null,
	"br_4" decimal not null,
	"br_5" decimal not null,
	"hv_lt_150k" decimal not null,
	"hv_150_300k" decimal not null,
	"hv_300_500k" decimal not null,
	"hv_gt_500k" decimal not null,
	"med_hv" decimal not null,
	"tot_emp_res" decimal not null,
	"res_naics1_type" varchar not null,
	"res_naics2_type" varchar not null,
	"res_naics3_type" varchar not null,
	"res_naics4_type" varchar not null,
	"res_naics5_type" varchar not null,
	"res_naics1_count" decimal not null,
	"res_naics2_count" decimal not null,
	"res_naics3_count" decimal not null,
	"res_naics4_count" decimal not null,
	"res_naics5_count" decimal not null,
	"tot_emp_work" decimal not null,
	"work_naics1_type" varchar not null,
	"work_naics2_type" varchar not null,
	"work_naics3_type" varchar not null,
	"work_naics4_type" varchar not null,
	"work_naics5_type" varchar not null,
	"work_naics1_count" decimal not null,
	"work_naics2_count" decimal not null,
	"work_naics3_count" decimal not null,
	"work_naics4_count" decimal not null,
	"work_naics5_count" decimal not null,
	"res_city1_type" varchar not null,
	"res_city2_type" varchar not null,
	"res_city3_type" varchar not null,
	"res_city4_type" varchar not null,
	"res_city5_type" varchar not null,
	"res_city1_count" decimal not null,
	"res_city2_count" decimal not null,
	"res_city3_count" decimal not null,
	"res_city4_count" decimal not null,
	"res_city5_count" decimal not null,
	"work_city1_type" varchar not null,
	"work_city2_type" varchar not null,
	"work_city3_type" varchar not null,
	"work_city4_type" varchar not null,
	"work_city5_type" varchar not null,
	"work_city1_count" decimal not null,
	"work_city2_count" decimal not null,
	"work_city3_count" decimal not null,
	"work_city4_count" decimal not null,
	"work_city5_count" decimal not null,
	"medincfam_hcost" boolean,
	"medincfam_tcost" boolean,
	"medincfam_htcost" boolean,
	"ret_hcost" boolean,
	"ret_tcost" boolean,
	"ret_htcost" boolean,
	"spfam_hcost" boolean,
	"spfam_tcost" boolean,
	"spfam_htcost" boolean,
	"modincfam_hcost" boolean,
	"modincfam_tcost" boolean,
	"modincfam_htcost" boolean,
	"ides_emp" boolean,
	"emp_change" boolean,
	"pct_change" boolean,
	"avg_vmt" decimal not null,
	"ret_sales" boolean,
	"res_eav" boolean,
	"cmrcl_eav" boolean,
	"ind_eav" boolean,
	"rail_eav" boolean,
	"farm_eav" boolean,
	"min_eav" boolean,
	"tot_eav" boolean,
	"walkscore" boolean,
	"open_space_per_1000" decimal not null,
	"tot_acres" decimal not null,
	"sf" decimal not null,
	"sfperc" decimal not null,
	"mf" decimal not null,
	"mfperc" decimal not null,
	"mix" decimal,
	"mixperc" decimal,
	"comm" decimal not null,
	"commperc" decimal not null,
	"inst" decimal not null,
	"instperc" decimal not null,
	"ind" decimal,
	"indperc" decimal,
	"trans" decimal not null,
	"transperc" decimal not null,
	"ag" decimal,
	"agperc" decimal,
	"open" decimal not null,
	"openperc" decimal not null,
	"vacant" decimal not null,
	"vacperc" decimal not null
);
